### ISSUE TITLE
Small problem with the Floss during an analysis of an old malware (ZeusBanking)

### ISSUE THREAD

**Issue by alexandreborges** [fireeye/flare-floss#126] opened 2016-05-01 03:16 UTC
While performing few tests using Floss, I found an error during a quick analysis of the ZeusBanking (version Nov/2013): 

```
root@kali:~# /root/floss -v -a invoice_2318362983713_823931342io.pdf.exe

....(snip)...
0x0003D8DD   4	5
0x0003D8E1   5#555<5V5
0x0003D90D   4P5
0x0003D921   9(909

Static UTF-16 strings
Offset       String
----------   -------------------------------------
0x00001450   @5-
0x0000988B   @5O
0x000311BC    !"#$%&'()*+,-./0123456789:;<

Traceback (most recent call last):
  File "<string>", line 409, in <module>
  File "<string>", line 374, in main
  File "site-packages/viv_utils/__init__.py", line 34, in getWorkspace
  File "site-packages/vivisect/__init__.py", line 2107, in loadFromFile
  File "site-packages/vivisect/parsers/pe.py", line 30, in parseFile
  File "site-packages/vivisect/parsers/pe.py", line 96, in loadPeIntoWorkspace
  File "site-packages/PE/__init__.py", line 408, in getDllName
  File "site-packages/PE/__init__.py", line 1035, in __getattr__
  File "site-packages/PE/__init__.py", line 892, in parseExports
IndexError: tuple index out of range
main returned -1
```

I hope it can help you to improve the tool. 

Have a nice day.

Alexandre Borges.

**Comment by williballenthin** [comment] 2016-05-01 21:20
Hi Alexandre,

Thanks for reporting this issue. I hope we can fix it soon for you!

Can you share the sample?

**Comment by williballenthin** [comment] 2016-05-01 21:20
looks like an issue with vivisect's PE parser

**Comment by alexandreborges** [comment] 2016-05-01 22:05
Hi Willi,

 

Good evening. How are you?

 

Sure, I can. It follows the sample attached. The password is infected. 

 

I’ve faced problems with other different samples, but I’m trying to avoid overloading you with more problems. 

 

Finally, I’ve written a very quick post about Floss (https://alexandreborges.org/2016/05/01/initial-static-analysis-using-floss/) because professionals need know about it. 

 

Thank you for your message and have a nice day.

 

Alexandre.

 

 

De: Willi Ballenthin [mailto:notifications@github.com] 
Enviada em: domingo, 1 de maio de 2016 18:20
Para: fireeye/flare-floss
Cc: alexandreborges; Author
Assunto: Re: [fireeye/flare-floss] Small problem with the Floss during an analysis of an old malware (ZeusBanking) (#126)

 

Hi Alexandre,

Thanks for reporting this issue. I hope we can fix it soon for you!

Can you share the sample?

**Comment by williballenthin** [comment] 2016-05-01 23:12
would you mind uploading the file to a third party site, or emailing me (wilbal1087@gmail.com) and Moritz (moritz.raabe@fireeye.com) with the file? github didn't attach the file to the issue tracker on github.

also, please feel free to report as many issues as you! hopefully we can close out many at the same time with a bit of planning.

**Comment by williballenthin** [comment] 2016-05-06 15:57
hi @alexandreborges without access to the sample we won't be able to fix the bug. would you please upload the file to a shared workspace, or email it directly to us?

**Comment by mr-tz** [comment] 2016-05-06 19:00
I can reproduce the error with the file with MD5 hash EA039A854D20D7734C5ADD48F1A51C34.
Is that the sample you were looking at, @alexandreborges?

**Comment by alexandreborges** [comment] 2016-05-06 19:30
Willi,

 

Good afternoon. How are you?

 

Last Sunday night, I sent the sample, according to your request, for your personal e-mail on Gmail and Moritz. Did you receive it? I can retransmit it again.

 

Have a nice day and thanks for the message. 

 

Alexandre. 

 

De: Willi Ballenthin [mailto:notifications@github.com] 
Enviada em: sexta-feira, 6 de maio de 2016 12:58
Para: fireeye/flare-floss
Cc: alexandreborges; Mention
Assunto: Re: [fireeye/flare-floss] Small problem with the Floss during an analysis of an old malware (ZeusBanking) (#126)

 

hi @alexandreborges <https://github.com/alexandreborges>  without access to the sample we won't be able to fix the bug. would you please upload the file to a shared workspace, or email it directly to us?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub <https://github.com/fireeye/flare-floss/issues/126#issuecomment-217483431>   <https://github.com/notifications/beacon/AMjivVDpGWTS2FXOtUEuOn0mvjGZVsBRks5p-2UCgaJpZM4ITi0H.gif> 



---
Este email foi escaneado pelo Avast antivírus.
https://www.avast.com/antivirus

**Comment by williballenthin** [comment] 2016-05-06 19:34
hey @alexandreborges no, I didn't get the email (just checked again on gmail, and still don't see it). When you have a moment (no rush!) would you send the sample again?

**Comment by alexandreborges** [comment] 2016-05-06 19:35
Moritz,

 

Good afternoon. How are you?

 

Last Sunday I sent you the sample to your e-mail on FireEye. Did you receive it?

 

About your question, it is the same sample. See the output below, please:

 

root@kali # md5sum invoice_2318362983713_823931342io.pdf.exe 

ea039a854d20d7734c5add48f1a51c34  invoice_2318362983713_823931342io.pdf.exe

 

Have a nice day, Moritz.

 

Alexandre.

 

 

De: mr-tz [mailto:notifications@github.com] 
Enviada em: sexta-feira, 6 de maio de 2016 16:00
Para: fireeye/flare-floss
Cc: alexandreborges; Mention
Assunto: Re: [fireeye/flare-floss] Small problem with the Floss during an analysis of an old malware (ZeusBanking) (#126)

 

I can reproduce the error with the file with MD5 hash EA039A854D20D7734C5ADD48F1A51C34.
Is that the sample you were looking at, @alexandreborges <https://github.com/alexandreborges> ?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub <https://github.com/fireeye/flare-floss/issues/126#issuecomment-217530310>   <https://github.com/notifications/beacon/AMjivfIRgZjVkExPO9m_djUjDTqTyAY0ks5p-4_KgaJpZM4ITi0H.gif> 



---
Este email foi escaneado pelo Avast antivírus.
https://www.avast.com/antivirus

**Comment by mr-tz** [comment] 2016-05-06 19:39
Thanks, we have the sample.

**Comment by williballenthin** [comment] 2016-05-06 20:09
this is an issue with the PE parser in vivisect. i will be reporting the issue and submitting a fix upstream.

this sample has some of the structures needed to export routines, but not all of them. specifically, the name and ordinal tables have a bunch of entries, but the function pointer table has no entries. vivisect assumes that this table will have at least one entry. the fix is to bail early if there are no entries in the function pointer table.

**Comment by williballenthin** [comment] 2016-05-06 20:17
fixed in upstream vivisect. nightly builds should pick up this change today.

**Comment by williballenthin** [comment] 2016-05-06 20:18
vivisect PR is https://github.com/vivisect/vivisect/pull/129

**Closed by williballenthin** 2016-05-06 20:17 UTC
Labels: bug
